spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/swasthyaqueue
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

spring.data.redis.host=localhost
spring.data.redis.port=6379

#Connecting to .env file
spring.config.import=optional:file:.env[.properties],optional:file:backend/.env[.properties]
jwt.secret=${JWT_SECRET}